[package]
name = "falling_sand_rust"
version = "0.1.0"
edition = "2021"
authors = ["DavidM"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.0-rc1"
rand = "0.7.3"
vulkano = "0.30.0"
bytemuck = "1.8.0"
